### ISSUE TITLE
Product VAT is not including to total price.

### ISSUE THREAD

**Issue by makbulut** [PayU/alu-client-php#14] opened 2016-04-25 11:54 UTC
$product->withCode($sepetPaketObject->getPaketId())
                ->withName($sepetPaketObject->getPaketAdi())
                ->withPrice($sepetPaketObject->getPaketFiyat())
                ->withQuantity($sepetPaketObject->getAdet())
                ->withVAT(18);

**Comment by drealecs** [comment] 2016-04-25 12:59
This is not a bug of ALU library.

Please get in contact with the integration department to make sure that order VAT is collected for the merchant account you are using.
The logic to collect or not VAT depends on multiple things and some of them are internal operational settings. Also billing country can change the behavior from what I remember.

I'll close the issue now.

**Closed by drealecs** 2016-04-25 12:59 UTC
